---
version: 1
table:
  name: "products"
  pattern: "products.*.xml"
  attributes:
  - name: "category"
    type: "string"
    array: false
    sample: "Pies"
  - name: "cost"
    type: "double"
    array: false
    sample: "9.66"
  - name: "description"
    type: "string"
    array: false
    sample: "Description for Whole Wheat Bread"
  - name: "name"
    type: "string"
    array: false
    sample: "Whole Wheat Bread"
  - name: "price"
    type: "double"
    array: false
    sample: "8.68"
  - name: "product_id"
    type: "long"
    array: false
    sample: "9"
  metadata:
    format: "XML"
    encoding: "UTF-8"
    withHeader: true
    options:
      rowTag: "record"
    writeStrategy:
      type: "OVERWRITE"
  sample: "{\"category\":\"Cakes\",\"cost\":14.55,\"description\":\"Description for\
    \ Chocolate Cake\",\"name\":\"Chocolate Cake\",\"price\":17.12,\"product_id\"\
    :1}\n{\"category\":\"Cakes\",\"cost\":12.5,\"description\":\"Description for Vanilla\
    \ Cake\",\"name\":\"Vanilla Cake\",\"price\":14.71,\"product_id\":2}\n{\"category\"\
    :\"Cakes\",\"cost\":24.57,\"description\":\"Description for Carrot Cake\",\"name\"\
    :\"Carrot Cake\",\"price\":28.91,\"product_id\":3}\n{\"category\":\"Cookies\"\
    ,\"cost\":17.89,\"description\":\"Description for Chocolate Chip Cookies\",\"\
    name\":\"Chocolate Chip Cookies\",\"price\":21.05,\"product_id\":4}\n{\"category\"\
    :\"Cookies\",\"cost\":7.38,\"description\":\"Description for Gingerbread Cookies\"\
    ,\"name\":\"Gingerbread Cookies\",\"price\":8.68,\"product_id\":5}\n{\"category\"\
    :\"Cookies\",\"cost\":23.64,\"description\":\"Description for Sugar Cookies\"\
    ,\"name\":\"Sugar Cookies\",\"price\":27.81,\"product_id\":6}\n{\"category\":\"\
    Breads\",\"cost\":14.5,\"description\":\"Description for Baguette\",\"name\":\"\
    Baguette\",\"price\":17.06,\"product_id\":7}\n{\"category\":\"Breads\",\"cost\"\
    :12.75,\"description\":\"Description for Whole Wheat Bread\",\"name\":\"Whole\
    \ Wheat Bread\",\"price\":15.0,\"product_id\":8}\n{\"category\":\"Breads\",\"\
    cost\":9.66,\"description\":\"Description for Croissant\",\"name\":\"Croissant\"\
    ,\"price\":11.36,\"product_id\":9}\n{\"category\":\"Pies\",\"cost\":15.45,\"description\"\
    :\"Description for Apple Pie\",\"name\":\"Apple Pie\",\"price\":18.18,\"product_id\"\
    :10}\n{\"category\":\"Pies\",\"cost\":9.11,\"description\":\"Description for Blueberry\
    \ Pie\",\"name\":\"Blueberry Pie\",\"price\":10.72,\"product_id\":11}\n{\"category\"\
    :\"Pies\",\"cost\":14.31,\"description\":\"Description for Pecan Pie\",\"name\"\
    :\"Pecan Pie\",\"price\":16.84,\"product_id\":12}"
