application:
  connectionRef: {{connection}}
  connections:
    postgres:
      type: JDBC
      options:
        url: "jdbc:postgresql://{{POSTGRES_HOST}}:{{POSTGRES_PORT}}/{{POSTGRES_DATABASE}}"
        driver: "org.postgresql.Driver"
        user: {{DATABASE_USER}}
        password: {{DATABASE_PASSWORD}}
        quoteIdentifiers: false
    spark-postgres:
      type: JDBC
      sparkFormat: jdbc
      options:
        url: "jdbc:postgresql://{{POSTGRES_HOST}}:{{POSTGRES_PORT}}/{{POSTGRES_DATABASE}}"
        driver: "org.postgresql.Driver"
        user: {{DATABASE_USER}}
        password: {{DATABASE_PASSWORD}}
        quoteIdentifiers: false
