ignore:
  - "src/main/scala/ai/starlake/job/Main"
  - "src/main/scala/ai/starlake/repl/Main.scala"
  - "src/main/scala/com/ebiznext/comet/job/Main.scala"
  - "src/main/scala/ai/starlake/job/atlas/AtlasJob.scala"
  - "src/main/scala/ai/starlake/schema/model/atlas/AtlasModel.scala"
  - "src/main/scala/ai/starlake/schema/model/atlas/AtlasData.scala"
  - "src/main/scala/ai/starlake/serve/SingleUserMainServer.scala"
