#!/usr/bin/env bash
set -euo pipefail

# ============================================================================
# Starlake Release Script
#
# Usage:
#   ./release.sh                    # Full release: publish + bump + rebuild
#   ./release.sh 1.5.9-SNAPSHOT     # Full release with specific next version
#   ./release.sh --dry-run 1.5.9-SNAPSHOT  # Preview version bump without changes
#   ./release.sh --skip-release 1.5.9-SNAPSHOT  # Skip Sonatype, just bump versions
# ============================================================================

SCRIPT_DIR="$( cd "$( dirname -- "${BASH_SOURCE[0]}" )" && pwd )"

# Parse args
DRY_RUN=false
SKIP_RELEASE=false
while [[ "${1:-}" == --* ]]; do
  case "$1" in
    --dry-run)      DRY_RUN=true; shift ;;
    --skip-release) SKIP_RELEASE=true; shift ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

# --- 1. Read current version from version.sbt (single source of truth) ---
CURRENT_VERSION=$(sed -n 's/.*"\(.*\)".*/\1/p' "$SCRIPT_DIR/version.sbt")
echo "Current version: $CURRENT_VERSION"

# Repo paths
API_DIR="${SL_API_DIR:-$HOME/git/starlake-api}"

# --- 2. Release current version to Sonatype ---
if [[ "$DRY_RUN" == false && "$SKIP_RELEASE" == false ]]; then
  # --- 2a. Release starlake-core ---
  echo ""
  echo "============================================"
  echo "Step 1a: Releasing starlake-core $CURRENT_VERSION to Sonatype"
  echo "============================================"
  read -p "Proceed with starlake-core release? [y/N]: " CONFIRM
  if [[ "$CONFIRM" =~ ^[Yy]$ ]]; then
    cd "$SCRIPT_DIR"
    RELEASE_SONATYPE=true sbt 'release with-defaults'
    echo "starlake-core release published."
  else
    echo "starlake-core release skipped."
  fi

  # --- 2b. Release starlake-api ---
  if [[ -d "$API_DIR" ]]; then
    echo ""
    echo "============================================"
    echo "Step 1b: Releasing starlake-api $CURRENT_VERSION to Sonatype"
    echo "============================================"
    read -p "Proceed with starlake-api release? [y/N]: " CONFIRM_API
    if [[ "$CONFIRM_API" =~ ^[Yy]$ ]]; then
      cd "$API_DIR"
      RELEASE_SONATYPE=true sbt 'release with-defaults'
      echo "starlake-api release published."
    else
      echo "starlake-api release skipped."
    fi
    cd "$SCRIPT_DIR"
  else
    echo "Skipping starlake-api release (directory not found: $API_DIR)"
  fi
fi

# --- 3. Determine next version ---
echo ""
echo "============================================"
echo "Step 2: Bump to next SNAPSHOT version"
echo "============================================"
if [[ -n "${1:-}" ]]; then
  NEXT_VERSION="$1"
else
  # Auto-suggest: increment patch number
  BASE=$(echo "$CURRENT_VERSION" | sed 's/-SNAPSHOT//')
  MAJOR=$(echo "$BASE" | cut -d. -f1)
  MINOR=$(echo "$BASE" | cut -d. -f2)
  PATCH=$(echo "$BASE" | cut -d. -f3)
  SUGGESTED="$MAJOR.$MINOR.$((PATCH + 1))-SNAPSHOT"
  read -p "Next version [$SUGGESTED]: " NEXT_VERSION
  NEXT_VERSION="${NEXT_VERSION:-$SUGGESTED}"
fi

echo "Bumping: $CURRENT_VERSION -> $NEXT_VERSION"
echo ""

# --- 3. Define all files that contain the version ---

# Core repo (this repo)
CORE_FILES=(
  "$SCRIPT_DIR/version.sbt"
  # Setup.java no longer needs updating — it reads the version from
  # starlake-version.properties generated by SBT at build time
)

# Local starlake installation
STARLAKE_HOME="${STARLAKE_HOME:-$HOME/starlake}"
LOCAL_FILES=(
  "$STARLAKE_HOME/versions.sh"
)

# starlake-api repo
API_FILES=(
  "$API_DIR/version.sbt"
  "$API_DIR/build.sbt"
  "$API_DIR/.versions"
  "$API_DIR/versions.sh"
)

# starlake-ui2 repo
UI_DIR="${SL_UI_DIR:-$HOME/git/starlake-ui2}"
UI_FILES=(
  "$UI_DIR/.versions"
  "$UI_DIR/Dockerfile"
  "$UI_DIR/.github/workflows/docker-hub-amd-arm.yml"
)

# Combine all
ALL_FILES=("${CORE_FILES[@]}" "${LOCAL_FILES[@]}" "${API_FILES[@]}" "${UI_FILES[@]}")

# --- 4. Replace version in all files that reference the current version ---
UPDATED=0
SKIPPED=0

for file in "${ALL_FILES[@]}"; do
  if [[ -f "$file" ]]; then
    if grep -q "$CURRENT_VERSION" "$file"; then
      if [[ "$DRY_RUN" == true ]]; then
        echo "[DRY-RUN] Would update: $file"
      else
        sed -i'' -e "s/$CURRENT_VERSION/$NEXT_VERSION/g" "$file"
        echo "Updated: $file"
      fi
      ((UPDATED++))
    else
      echo "Skipped (version not found): $file"
      ((SKIPPED++))
    fi
  else
    echo "Skipped (file missing): $file"
    ((SKIPPED++))
  fi
done

echo ""
echo "Updated: $UPDATED files, Skipped: $SKIPPED files"

if [[ "$DRY_RUN" == true ]]; then
  echo ""
  echo "[DRY-RUN] No files were modified."
  exit 0
fi

# --- 5. Update LOCAL_STARLAKE_VERSION in bash profile ---
PROFILE="$HOME/.bash_profile"
if [[ -f "$PROFILE" ]] && grep -q "LOCAL_STARLAKE_VERSION" "$PROFILE"; then
  sed -i'' -e "s/LOCAL_STARLAKE_VERSION=.*/LOCAL_STARLAKE_VERSION=$NEXT_VERSION/" "$PROFILE"
  echo "Updated LOCAL_STARLAKE_VERSION in $PROFILE"
  echo "Run: source $PROFILE"
fi

# --- 6. Rebuild setup and assembly ---
echo ""
echo "============================================"
echo "Step 3: Rebuild"
echo "============================================"
read -p "Run 'sbt clean compile packageSetup' + './tmpsbt.sh'? [y/N]: " REBUILD
if [[ "$REBUILD" =~ ^[Yy]$ ]]; then
  cd "$SCRIPT_DIR"
  source "$PROFILE" 2>/dev/null || true
  sbt clean compile packageSetup
  if [[ -x "$SCRIPT_DIR/tmpsbt.sh" ]]; then
    "$SCRIPT_DIR/tmpsbt.sh"
  fi
  echo "Rebuild complete."
fi

echo ""
echo "============================================"
echo "Release complete: $CURRENT_VERSION released, now on $NEXT_VERSION"
echo ""
echo "Remaining steps:"
echo "  1. Commit & push starlake-core"
echo "  2. Commit & push starlake-api"
echo "  3. Commit & push starlake-ui2"
echo "  4. Rebuild docker images"
echo "============================================"