# Use the official Apache Airflow image as the base
FROM apache/airflow:latest

# Switch to root user to install additional packages
USER root

# Install docker client and NFS client utilities
RUN apt-get update \
    && apt-get install -y nfs-common \
    docker.io \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY scripts/starlake-airflow.sh /usr/local/bin/starlake
RUN chmod +x /usr/local/bin/starlake

# Switch back to the airflow user
USER airflow

# Install SL Python libraries
RUN pip install --no-cache-dir \
    starlake-orchestration[airflow] --upgrade
