# Use the official Apache Airflow image as the base
FROM apache/airflow:latest

# Switch to root user to install additional packages
USER root

# Install docker client and NFS client utilities
RUN apt-get update \
    && apt-get install -y nfs-common \
    docker.io \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ADD conf/airflow/webserver_config.py /opt/airflow/webserver_config.py

# Required to mount NFS volumes
RUN echo "airflow ALL=(ALL:ALL) NOPASSWD: ALL"  > /etc/sudoers.d/airflow

# Install SL CLI
RUN mkdir -p /app/starlake
COPY scripts/docker/starlake.sh /app/starlake/starlake
RUN chmod +x /app/starlake/starlake
RUN ln -s /app/starlake/starlake /usr/local/bin/starlake

# Switch back to the airflow user
USER airflow

# Install SL Python libraries
RUN pip install --no-cache-dir \
    starlake-orchestration[airflow] --upgrade

