#!/bin/bash
set -e

ENABLE_BIGQUERY=${ENABLE_BIGQUERY:-1}
ENABLE_AZURE=${ENABLE_AZURE:-1}
ENABLE_SNOWFLAKE=${ENABLE_SNOWFLAKE:-1}
ENABLE_POSTGRESQL=${ENABLE_POSTGRESQL:-1}
ENABLE_REDSHIFT=${ENABLE_REDSHIFT:-1}

# STARLAKE
SL_VERSION=${SL_VERSION:-1.0.0-SNAPSHOT}

# SPARK
SCALA_VERSION=${SCALA_VERSION:-2.12}
SPARK_VERSION=${SPARK_VERSION:-3.5.0}
HADOOP_VERSION=${HADOOP_VERSION:-3}

# BIGQUERY
SPARK_BQ_VERSION=${SPARK_BQ_VERSION:-0.34.0}

# AZURE
HADOOP_AZURE_VERSION=${HADOOP_AZURE_VERSION:-3.3.5}
AZURE_STORAGE_VERSION=${AZURE_STORAGE_VERSION:-8.6.6}
JETTY_VERSION=${JETTY_VERSION-9.4.51.v20230217}


# SNOWFLAKE
SPARK_SNOWFLAKE_VERSION=${SPARK_SNOWFLAKE_VERSION:-3.4}
SNOWFLAKE_JDBC_VERSION=${SNOWFLAKE_JDBC_VERSION:-3.14.0}

# POSTGRESQL
POSTGRESQL_VERSION=${POSTGRESQL_VERSION:-42.5.4}

# REDSHIFT
AWS_JAVA_SDK_VERSION=${AWS_JAVA_SDK_VERSION:-1.12.595}
HADOOP_AWS_VERSION=${HADOOP_AWS_VERSION:-3.3.4}
REDSHIFT_JDBC_VERSION=${REDSHIFT_JDBC_VERSION:-2.1.0.23}
SPARK_REDSHIFT_VERSION=${SPARK_REDSHIFT_VERSION:-6.1.0-spark_3.5}


