@ECHO OFF

:: SET ENABLE_BIGQUERY=1
:: SET ENABLE_AZURE=1
:: SET ENABLE_SNOWFLAKE=1
:: SET ENABLE_POSTGRESQL=1
:: SET ENABLE_REDSHIFT=1

:: SET # STARLAKE
:: SET SL_VERSION=1.0.0-SNAPSHOT

:: SET # SPARK
:: SET SCALA_VERSION=2.12
:: SET SPARK_VERSION=3.5.0
:: SET HADOOP_VERSION=3

:: SET # BIGQUERY
:: SET SPARK_BQ_VERSION=0.34.0

:: SET # AZURE
:: SET HADOOP_AZURE_VERSION=3.3.5
:: SET AZURE_STORAGE_VERSION=8.6.6
:: SET JETTY_VERSION=9.4.51.v20230217

:: SET # SNOWFLAKE
:: SET SPARK_SNOWFLAKE_VERSION=3.4
:: SET SNOWFLAKE_JDBC_VERSION=3.14.0

:: SET # POSTGRESQL
:: SET POSTGRESQL_VERSION=42.5.4

:: SET # REDSHIFT
:: SET AWS_JAVA_SDK_VERSION=1.12.595
:: SET HADOOP_AWS_VERSION=3.3.4
:: SET REDSHIFT_JDBC_VERSION=2.1.0.23
:: SET SPARK_REDSHIFT_VERSION=6.1.0-spark_3.5



if "%ENABLE_BIGQUERY%"=="" (
    SET ENABLE_BIGQUERY=1
)


if "%ENABLE_AZURE%"=="" (
    SET ENABLE_AZURE=1
)

if "%ENABLE_SNOWFLAKE%"=="" (
    SET ENABLE_SNOWFLAKE=1
)

if "%ENABLE_POSTGRESQL%"=="" (
    SET ENABLE_POSTGRESQL=1
)

if "%ENABLE_REDSHIFT%"=="" (
    SET ENABLE_REDSHIFT=1
)

:: STARLAKE
if "%SL_VERSION%"=="" (
    SET SL_VERSION=1.0.0-SNAPSHOT
)

:: SPARK
if "%SCALA_VERSION%"=="" (
    SET SCALA_VERSION=2.12
)

if "%SPARK_VERSION%"=="" (
    SET SPARK_VERSION=3.5.0
)

if "%HADOOP_VERSION%"=="" (
    SET HADOOP_VERSION=3
)

:: BIGQUERY
if "%SPARK_BQ_VERSION%"=="" (
    SET SPARK_BQ_VERSION=0.34.0
)

:: AZURE
if "%HADOOP_AZURE_VERSION%"=="" (
    SET HADOOP_AZURE_VERSION=3.3.5
)
if "%AZURE_STORAGE_VERSION%"=="" (
    SET AZURE_STORAGE_VERSION=8.6.6
)
if "%JETTY_VERSION%"=="" (
    SET JETTY_VERSION=9.4.51.v20230217
)

:: SNOWFLAKE
if "%SPARK_SNOWFLAKE_VERSION%"=="" (
    SET SPARK_SNOWFLAKE_VERSION=3.4
)
if "%SNOWFLAKE_JDBC_VERSION%"=="" (
    SET SNOWFLAKE_JDBC_VERSION=3.14.0
)

:: POSTGRESQL
if "%POSTGRESQL_VERSION%"=="" (
    SET POSTGRESQL_VERSION=42.5.4
)

:: REDSHIFT
if "%AWS_JAVA_SDK_VERSION%"=="" (
    SET AWS_JAVA_SDK_VERSION=1.12.595
)
if "%HADOOP_AWS_VERSION%"=="" (
    SET HADOOP_AWS_VERSION=3.3.4
)
if "%REDSHIFT_JDBC_VERSION%"=="" (
    SET REDSHIFT_JDBC_VERSION=2.1.0.23
)
if "%SPARK_REDSHIFT_VERSION%"=="" (
    SET SPARK_REDSHIFT_VERSION=6.1.0-spark_3.5
)


