application:
  connectionRef: {{connection}}
  connections:
    snowflake:
      type: jdbc
      options:
        url: "jdbc:snowflake://{{SNOWFLAKE_ACCOUNT}}.snowflakecomputing.com"
        driver: "net.snowflake.client.jdbc.SnowflakeDriver"
        user: {{SNOWFLAKE_USER}}
        password: {{SNOWFLAKE_PASSWORD}}
        warehouse: {{SNOWFLAKE_WAREHOUSE}}
        db: {{SNOWFLAKE_DB}}
        keep_column_case: "off"
        preactions: "alter session set TIMESTAMP_TYPE_MAPPING = 'TIMESTAMP_LTZ';ALTER SESSION SET QUOTED_IDENTIFIERS_IGNORE_CASE = true"
    spark-snowflake:
      type: jdbc
      sparkFormat: snowflake
      options:
        sfUrl: "{{SNOWFLAKE_ACCOUNT}}.snowflakecomputing.com" # make sure you do not prefix by jdbc:snowflake://. This is done by the snowflaek driver
        #sfDriver: "net.snowflake.client.jdbc.SnowflakeDriver"
        sfUser: {{SNOWFLAKE_USER}}
        sfPassword: {{SNOWFLAKE_PASSWORD}}
        sfWarehouse: {{SNOWFLAKE_WAREHOUSE}}
        sfDatabase: {{SNOWFLAKE_DB}}
        keep_column_case: "off"
        autopushdown: on
        preactions: "alter session set TIMESTAMP_TYPE_MAPPING = 'TIMESTAMP_LTZ';ALTER SESSION SET QUOTED_IDENTIFIERS_IGNORE_CASE = true"
