version: 1
application:
  connectionRef: "{{ connection }}"
  loader: native
  connections:
    bigquery:
      # When accessing from your desktop, do not forget to set GOOGLE_APPLICATION_CREDENTIALS to your application credentials file
      # example on MacOS: export GOOGLE_APPLICATION_CREDENTIALS="$HOME/.config/gcloud/application_default.json"
      type: "bigquery"
      options:
        #gcsBucket: "starlake-app" # Temporary GCS Bucket where intermediary files will be stored. Required in indirect mode only
        writeMethod: "direct" # direct or indirect (indirect is required for certain features when using Spark see https://github.com/GoogleCloudDataproc/spark-bigquery-connector)
        location: "europe-west1" # EU or US or ..
        authType: "APPLICATION_DEFAULT"
        authScopes: "https://www.googleapis.com/auth/cloud-platform" # comma separated list of scopes
        #authType: SERVICE_ACCOUNT_JSON_KEYFILE
        #jsonKeyfile: "/Users/me/.gcloud/keys/starlake-me.json"
        #authType: "ACCESS_TOKEN"
        #gcpAccessToken: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    duckdb:
      type: "jdbc" # Connection to DuckDB
      options:
        url: "jdbc:duckdb:{{SL_ROOT}}/datasets/duckdb.db" # Location of the DuckDB database
        driver: "org.duckdb.DuckDBDriver"
  accessPolicies: # Required to set RLS and ACLs on tables
    apply: true
    location: europe-west1
    taxonomy: GDPR
  spark:
    datasource:
      bigquery:
        allowFieldAddition: "true" # Allow schema updates. To disable, set it to false
        allowFieldRelaxation: "true" # Allow schema updates. To disable, set it to false

