load:
  name: "sales"
  metadata:
    directory: "{{root_path}}/incoming/sales"
    format: "DSV"
    withHeader: true
    quote: "\""
    escape: "\\"
    write: "APPEND"
  tableRefs:
    - "_customers"
    - "_orders"
