load:
  name: "sales"
  metadata:
    directory: "{{root_path}}/incoming/sales"
    mode: "FILE"
    format: "DSV"
    withHeader: true
    quote: "\""
    escape: "\\"
    write: "APPEND"
      #timestamp: signup
